### DISCUSSION TITLE
文章页的IP归属地在哪里修改呀，主题文档没有看到。每次显示的都是长沙🤣

### DISCUSSION THREAD

**Discussion by youngdajie** [anzhiyu-c/hexo-theme-anzhiyu#207] [General]
文章页的IP归属地在哪里修改呀，主题文档没有看到。每次显示的都是长沙🤣

![1708397275444](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/79750210/a7898125-a916-4e38-be6c-22158e710948)

**Comment by AGEN233** [comment]
同问（

**Reply by youngdajie** [reply]
可以自己改源代码

**Comment by anzhiyu-c** [comment]
在文章md的顶部配置location
在主题的配置文件中配置默认位置
```
post_copyright:
  enable: true
  decode: false
  author_href:
  location: 长沙
 ```
 
 也可以在文章md的顶部配置
 ```
 post_copyright
   - location: "长沙"
 ```
