### DISCUSSION TITLE
home_top 这是为什么无法正常显示？

### DISCUSSION THREAD

**Discussion by zero617** [anzhiyu-c/hexo-theme-anzhiyu#279] [General]
![image](https://github.com/user-attachments/assets/308fa385-298c-43f2-864d-edeb3516d59a)

配置
```
# 首页顶部相关配置
home_top:
  enable: true # 开关
  timemode: date #date/updated
  title: 生活明朗
  subTitle: 万物可爱。
  siteText: zero617.top
  category:
    - name: 软件
      path: /categories/软件/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-dove
    - name: 技术
      path: /categories/技术/
      shadow: var(--anzhiyu-shadow-red)
      class: red
      icon: anzhiyu-icon-fire
    - name: 博客
      path: /categories/博客/
      shadow: var(--anzhiyu-shadow-green)
      class: green
      icon: anzhiyu-icon-book
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper:
    enable: true
    swiper_css: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.css #swiper css依赖
    swiper_js: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.js #swiper js依赖
  banner:
    tips: 啦啦啦
    title: 实验
    image: https://bu.dusays.com/2023/05/13/645fa3cf90d70.webp
    link: https://docs.anheyu.com/
```

**Comment by zippedalo** [comment]
在同一文件下，一般为 `_config.anzhiyu.yml`，有一个名为 `peoplecanvas` 的选项，其默认代码长这样：

```
# 首页随便逛逛people模式 而非技能点模式，关闭后为技能点模式需要配置creativity.yml
peoplecanvas:
  enable: false
  img: https://upload-bbs.miyoushe.com/upload/2023/09/03/125766904/ee23df8517f3c3e3efc4145658269c06_5714860933110284659.png
```

把它设置成false就没问题了
