### ISSUE TITLE
[Bug]: 使用github actions部署到pages成功后，pages页面空白

### ISSUE THREAD

**Issue by renyancheng** [anzhiyu-c/hexo-theme-anzhiyu#231]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

CI/CD yml:
```yml
name: Blog CI/CD # 脚本 workflow 名称

on:
  push:
    branches: [main, master] # 当监测 main,master 的 push
    paths: # 监测所有 source 目录下的文件变动，所有 yml,json 后缀文件的变动。
      - '*.json'
      - '**.yml'
      - '**/source/**'

jobs:
  blog: # 任务名称
    timeout-minutes: 30 # 设置 30 分钟超时
    runs-on: ubuntu-latest # 指定最新 ubuntu 系统
    steps:
      - uses: actions/checkout@v2 # 拉取仓库代码
      - uses: actions/setup-node@v2 # 设置 node.js 环境
      - name: Cache node_modules # 缓存 node_modules，提高编译速度，毕竟每月只有 2000 分钟。
        uses: actions/cache@v2 # 亲测 Github 服务器编译速度比我自己电脑都快，如果每次构建按5分钟计算，我们每个月可以免费部署 400 次，Github yyds！！！
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Init Node.js # 安装源代码所需插件
        run: |
          npm install
          echo "init node successful"
      - name: Install Hexo-cli # 安装 Hexo
        run: |
          npm install -g hexo-cli --save
          echo "install hexo successful"
      - name: Build Blog # 编译创建静态博客文件
        run: |
          hexo clean
          hexo g
          echo "build blog successful"
      - name: Deploy Blog # 设置 git 信息并推送静态博客文件
        run: |
          git config --global user.name "renyancheng"
          git config --global user.email "2441260435@qq.com"
          hexo deploy

      - run: echo "Deploy Successful!"
```

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/67620912/b094ef64-a97e-427b-92c1-8a49edfac252)

pages文件均部署成功，但访问[renyancheng.github.io](https://renyancheng.github.io/)页面空白，切换其他主题后页面可以正常访问无空白

### 出现问题的网站 | Website

https://renyancheng.github.io/
