### ISSUE TITLE
[Feature]: 希望支持配置bangumis的游戏页

### ISSUE THREAD

**Issue by SherlockerSun** [anzhiyu-c/hexo-theme-anzhiyu#252]
### 想要的功能 | What feature do you want?

同bangumis的追番页，配置游戏页，标签：在玩、想玩、玩过，内容：游戏封面、游戏名、评分等

bangumis配置如下
```yml
game: # 游戏设置，仅支持source: bgmv0
  enable: true
  path:
  source: bgmv0
  vmid:
  title: '游戏列表'
  quote: '生命不息，游戏不止！'
  show: 1
  lazyload: true
  srcValue: '__image__'
  lazyloadAttrName: 'data-src=__image__'
  loading:
  metaColor:
  color:
  webp:
  progress:
  extraOrder:
  order:
  extra_options:
    key: value
  coverMirror:
```
