### ISSUE TITLE
[Bug]: 首页随便逛逛people模式 图片失效

### ISSUE THREAD

**Issue by merriep** [anzhiyu-c/hexo-theme-anzhiyu#256]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

首页随便逛逛people模式 图片失效
![404](https://github.com/user-attachments/assets/fdb56c14-dc7b-4903-af77-8d4cb13a48cc)
```yaml
# 首页随便逛逛people模式 而非技能点模式，关闭后为技能点模式需要配置creativity.yml
peoplecanvas:
  enable: true
  img: https://upload-bbs.miyoushe.com/upload/2023/09/03/125766904/ee23df8517f3c3e3efc4145658269c06_5714860933110284659.png

```
配置文件中的 img 图片失效，望更新~

### 出现问题的网站 | Website

https://jokeroy.top/
