### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by AlphaMastar** [anzhiyu-c/hexo-theme-anzhiyu#27]
### 想要的功能 | What feature do you want?

主页面点开搜索后，页面滚动条消失，页面会向右边移动几个像素点。
想提个BUG，单好像又不算BUG，就在这提了，希望能满足我这强迫症的小小幻想捏

**Comment by anzhiyu-c** [comment]
不会支持，搜索打开后为单独的模态框，可以自行通过css完成。
```css
html {
    overflow: visible !important;
}
```
