### ISSUE TITLE
[Bug]: home_top挂了，无法正常显示

### ISSUE THREAD

**Issue by zero617** [anzhiyu-c/hexo-theme-anzhiyu#281]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/user-attachments/assets/308fa385-298c-43f2-864d-edeb3516d59a)

配置
```
# 首页顶部相关配置
home_top:
  enable: true # 开关
  timemode: date #date/updated
  title: 生活明朗
  subTitle: 万物可爱。
  siteText: zero617.top
  category:
    - name: 软件
      path: /categories/软件/
      shadow: var(--anzhiyu-shadow-blue)
      class: blue
      icon: anzhiyu-icon-dove
    - name: 技术
      path: /categories/技术/
      shadow: var(--anzhiyu-shadow-red)
      class: red
      icon: anzhiyu-icon-fire
    - name: 博客
      path: /categories/博客/
      shadow: var(--anzhiyu-shadow-green)
      class: green
      icon: anzhiyu-icon-book
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper:
    enable: true
    swiper_css: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.css #swiper css依赖
    swiper_js: https://npm.elemecdn.com/anzhiyu-theme-static@1.0.0/swiper/swiper.min.js #swiper js依赖
  banner:
    tips: 啦啦啦
    title: 实验
    image: https://bu.dusays.com/2023/05/13/645fa3cf90d70.webp
    link: https://docs.anheyu.com/
```

### 出现问题的网站 | Website

zero617.top

**Comment by zero617** [comment]
最好图标能自定义，参考solitude主题

**Comment by anzhiyu-c** [comment]
```
# 首页随便逛逛people模式 而非技能点模式，关闭后为技能点模式需要配置creativity.yml
peoplecanvas:
  enable: false
  img: https://upload-bbs.miyoushe.com/upload/2024/07/27/125766904/ba62475f396df9de3316a08ed9e65d86_5680958632268053399..png
  ```
  
  img改成这个
  
  图标自定义在技能点配置里面
