### ISSUE TITLE
[Bug]: 朋友圈“钓鱼”功能无法正确识别文章，显示为“undefined”

### ISSUE THREAD

**Issue by yutian81** [anzhiyu-c/hexo-theme-anzhiyu#282]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

"version": "1.6.12"

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

使用此项目部署了朋友圈：https://github.com/willow-god/Friend-Circle-Lite

后端使用cf pages部署，后端地址：https://anzhiyu-rss.pages.dev/，地址后加`all.json`即为数据文件

主题配置`_config.anzhiyu.yml`文件中朋友圈设置如下：
```
friends_vue:
  enable: true
  vue_js: https://pan.811520.xyz/cdn/friend_index.js
  apiurl: https://rss.811520.xyz/
  top_tips: 使用 友链朋友圈 订阅友链最新文章
  top_background: https://pan.811520.xyz/2024-10/1728111447377.webp
```
其中`https://pan.811520.xyz/cdn/friend_index.js`是根据作者文档中提供的js，修改里其中的后端变量

`https://rss.811520.xyz/` 是我的后端地址，加`all`或不加`all`都可以打开数据

但最终的结果是朋友圈可以正常呈现，钓鱼呈现出错，抓取不到文章

![image](https://github.com/user-attachments/assets/ccdb040b-9722-475f-aeb5-914aa0864145)

管理面板输入密码后没反应，无法登录：
![image](https://github.com/user-attachments/assets/75cf1b7d-2c78-4592-a815-d639676fdd0b)

### 出现问题的网站 | Website

https://blog.811520.xyz/
