### ISSUE TITLE
[Bug]: 关于非从1开始的有序序列序号显示不正确

### ISSUE THREAD

**Issue by ruoxijun** [anzhiyu-c/hexo-theme-anzhiyu#45]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.2.0

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在有序序列中默认序号 `::marker` 被 `::before` 代替并且使用了 `counter-increment: li 1;` 实现编号，但这也导致我非 **1** 开始的序列序号永远从 **1** 开始，如下图：

![微信截图_20230515102932](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/59528208/48280331-ffd8-490b-aebb-cd5fbe94e2ec)

### 出现问题的网站 | Website

https://ruoxijun.top/2020/08/29/java/springboot/SpringBoot/#3-IDEA-%E5%88%9B%E5%BB%BA%EF%BC%9A

**Comment by anzhiyu-c** [comment]
书写md文件时按照格式书写，img标签已经被认为是另起一行了，需要缩进书写，以便于hexo md解析器解析。

**Comment by ruoxijun** [comment]
> 

我知道我的书写方式是不合理的，但是你们的 bug 还是应该得到处理。
如图中 `<ol start="3">` 那么它的 `li` 理因从 3 开始，而不是从 1 另起。而重新启用 `::marker` 能有效的解决，或是使用其它的方案。

**Comment by anzhiyu-c** [comment]
hexo默认的渲染器是https://github.com/hexojs/hexo-renderer-marked 这个问题你应该去这个库处理，start="3"是渲染器加上的，主题只能处理css部分，如果使用:: marker并不能控制其样式，或许你可以换其他的hexo渲染器或者使用正确的书写方式。

**Comment by anzhiyu-c** [comment]
hexo默认的渲染器是https://github.com/hexojs/hexo-renderer-marked 这个问题你应该去这个库处理，start="3"是渲染器加上的，主题只能处理css部分，如果使用:: marker并不能控制其样式，或许你可以换其他的hexo渲染器或者使用正确的书写方式。

**Comment by ruoxijun** [comment]
[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked) 底层使用的 https://github.com/markedjs/marked 来渲染，渲染的结果是没有问题的。

问题来自你的 `themes\anzhiyu\source\css\_custom\code\code.css` 中：

```css
#article-container ol,
#article-container ul {
  margin-top: 0.4rem;
  padding: 0px 0px 0px 0.8rem;
  list-style: none;
  counter-reset: li 0;
}
```

`#article-container ol` 选择器和 `counter-reset: li 0;` 属性将所有 **ol** 的 **li** 计数器重置为 0。添加下面这段 css 代码可解决：

```css
#article-container ol[start] {
    counter-reset: unset;
}
```

* 后续问题：上面的 css 也只能解决从1开始有规律连续的序列，最保险的方案应该是添加一段 js 读取 ol 的 start 属性值来设置序号。
