### ISSUE TITLE
[Feature]: 在关于页中careers是否支持列表的形式

### ISSUE THREAD

**Issue by ashlee618** [anzhiyu-c/hexo-theme-anzhiyu#63]
### 想要的功能 | What feature do you want?

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/59916531/2739ea7b-59d6-474f-92cd-c1f534608e80)

```yaml
  careers:
    tips: 生涯
    title: 无限进步
    item:
      - 第一行
      - 第二行
    img: https://bu.dusays.com/2023/04/21/644287166329b.png
```

目前并不能实现以列表的形式进行展示，还是说当初就没有想过做成列表，hh
